packages: []
hoist: true
linkWorkspacePackages: false
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "typescript-eslint"
  - "@typescript-eslint/*"
  - "next"
  - "@next/*"
  - "@sentry/*"
  - "@sentry-internal/*"
onlyBuiltDependencies:
  - '@parcel/watcher'
  - electron
  - electron-winstaller
  - esbuild
  - lightningcss
publicHoistPattern:
  - "@kausal/themes"
  - "@kausal-private/themes-private"
  - "vite"
sharedWorkspaceLockfile: false
storeDir: ../.pnpm-store
