runner:
  eslint:
    cmd: node_modules/.bin/eslint --cache -f rdjson .
    format: rdjson
    filter-mode: nofilter
  typecheck:
    cmd: node_modules/.bin/tsc -b --pretty false
    format: tsc
    filter-mode: nofilter
