packages:
  - kausal_common
  - private/assistant
hoistPattern:
  - "@kausal/themes"
  - "@kausal-private/themes-private"
allowBuilds:
  "@parcel/watcher": false
  "@sentry-internal/node-cpu-profiler": false
  "@sentry/cli": false
  "@sentry/node-cpu-profiler": true
  "@swc/core": true
  es5-ext: false
  esbuild: false
  libxmljs2: false
  sharp: false
  unrs-resolver: false
dedupePeers: true
dedupePeerDependents: true
linkWorkspacePackages: false
strictPeerDependencies: true
resolvePeersFromWorkspaceRoot: true
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "typescript-eslint"
  - "@typescript-eslint/*"
  - "next"
  - "@next/*"
  - "@kausal/themes"
  - "@kausal-private/themes-private"
publicHoistPattern:
  - "@kausal/themes"
  - "@kausal-private/themes-private"
storeDir: ./.pnpm-store
peerDependencyRules:
  allowedVersions:
    react: "19"
    react-dom: "19"
