/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ModelRouteImport } from './routes/model'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NodeSlugRouteImport } from './routes/node.$slug'
import { Route as ActionsSlugRouteImport } from './routes/actions.$slug'

const ModelRoute = ModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NodeSlugRoute = NodeSlugRouteImport.update({
  id: '/node/$slug',
  path: '/node/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsSlugRoute = ActionsSlugRouteImport.update({
  id: '/actions/$slug',
  path: '/actions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/model': typeof ModelRoute
  '/actions/$slug': typeof ActionsSlugRoute
  '/node/$slug': typeof NodeSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/model': typeof ModelRoute
  '/actions/$slug': typeof ActionsSlugRoute
  '/node/$slug': typeof NodeSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/model': typeof ModelRoute
  '/actions/$slug': typeof ActionsSlugRoute
  '/node/$slug': typeof NodeSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$' | '/model' | '/actions/$slug' | '/node/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/model' | '/actions/$slug' | '/node/$slug'
  id: '__root__' | '/' | '/$' | '/model' | '/actions/$slug' | '/node/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ModelRoute: typeof ModelRoute
  ActionsSlugRoute: typeof ActionsSlugRoute
  NodeSlugRoute: typeof NodeSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/model': {
      id: '/model'
      path: '/model'
      fullPath: '/model'
      preLoaderRoute: typeof ModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/node/$slug': {
      id: '/node/$slug'
      path: '/node/$slug'
      fullPath: '/node/$slug'
      preLoaderRoute: typeof NodeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions/$slug': {
      id: '/actions/$slug'
      path: '/actions/$slug'
      fullPath: '/actions/$slug'
      preLoaderRoute: typeof ActionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ModelRoute: ModelRoute,
  ActionsSlugRoute: ActionsSlugRoute,
  NodeSlugRoute: NodeSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
